import os
#POSTGRES_USER=os.getenv('POSTGRES_USER')
#POSTGRES_PASSWORD=os.getenv('POSTGRES_PASSWORD')
#POSTGRES_HOST=os.getenv('POSTGRES_HOST')
#POSTGRES_PORT=os.getenv('POSTGRES_PORT')
#POSTGRES_DB='crop'

POSTGRES_USER='postgres'
POSTGRES_PASSWORD='postgres'
POSTGRES_HOST='127.0.0.1'
POSTGRES_PORT='8432'
POSTGRES_DB='crop'
EPSG_CODE=25830
TOLERANCE = 0.0001

